import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState } from 'react';

export default function Home() {
  const [name, setName] = useState('');
  const [type, setType] = useState('');
  const [contents, setContents] = useState('');
  const [containers, setContainers] = useState([]);
  const [translatedSrc, setTranslatedSrc] = useState([]);
  const [itemVault, setItemVault] = useState([
    {
      name: 'Abacus',
      type: 'Adventuring Gear',
      cost: '2 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Acid (vial)',
      type: 'Adventuring Gear',
      cost: '25 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Adamantine Ammunition',
      type: 'Ammunition, Generic Variant',
      cost: '—',
      weight: '—',
      source: 'XGE',
    },
    {
      name: 'Adamantine Weapon',
      type: 'Generic Variant',
      cost: '—',
      weight: '—',
      source: 'XGE',
    },
    {
      name: 'Airship',
      type: 'Vehicle',
      cost: '20,000 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Alchemist`s Fire (flask)',
      type: 'Adventuring Gear',
      cost: '50 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Alchemist`s Supplies',
      type: 'Artisan`s Tools',
      cost: '50 gp',
      weight: '8 lb.',
      source: 'PHB',
    },
    {
      name: 'Ale (Gallon)',
      type: 'Food and Drink',
      cost: '2 sp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Ale (Mug)',
      type: 'Food and Drink',
      cost: '4 cp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Amulet',
      type: 'Spellcasting Focus',
      cost: '5 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Antitoxin (vial)',
      type: 'Adventuring Gear',
      cost: '50 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Arcane Focus',
      type: 'Spellcasting Focus',
      cost: '—',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Arrow',
      type: 'Ammunition',
      cost: '5 cp',
      weight: '0.8 oz.',
      source: 'PHB',
    },
    {
      name: 'Arrows (20)',
      type: 'Ammunition',
      cost: '1 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Artisan`s Tools',
      type: 'Artisan`s Tools',
      cost: '—',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Assassin`s Blood',
      type: 'Adventuring Gear, Poison',
      cost: '150 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Backpack',
      type: 'Adventuring Gear',
      cost: '2 gp',
      weight: '5 lb.',
      source: 'PHB',
    },
    {
      name: 'Bagpipes',
      type: 'Instrument',
      cost: '30 gp',
      weight: '6 lb.',
      source: 'PHB',
    },
    {
      name: 'Ball Bearing',
      type: 'Adventuring Gear',
      cost: '0.1 cp',
      weight: '0.032 oz.',
      source: 'PHB',
    },
    {
      name: 'Ball Bearings (bag of 1,000)',
      type: 'Adventuring Gear',
      cost: '1 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Barding',
      type: 'Tack and Harness',
      cost: '×4',
      weight: '×2',
      source: 'PHB',
    },
    {
      name: 'Barrel',
      type: 'Adventuring Gear',
      cost: '2 gp',
      weight: '70 lb.',
      source: 'PHB',
    },
    {
      name: 'Basic Fishing Equipment',
      type: 'Adventuring Gear',
      cost: '1 sp',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Basic Poison (vial)',
      type: 'Adventuring Gear, Poison',
      cost: '100 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Basket',
      type: 'Adventuring Gear',
      cost: '4 sp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Battleaxe',
      type: 'Martial Weapon, Melee Weapon',
      cost: '10 gp',
      weight: '4 lb.',
      source: 'PHB',
    },
    {
      name: 'Bedroll',
      type: 'Adventuring Gear',
      cost: '1 gp',
      weight: '7 lb.',
      source: 'PHB',
    },
    {
      name: 'Bell',
      type: 'Adventuring Gear',
      cost: '1 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Birdpipes',
      type: 'Instrument',
      cost: '—',
      weight: '—',
      source: 'SCAG',
    },
    {
      name: 'Bit and bridle',
      type: 'Tack and Harness',
      cost: '2 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Black Sap',
      type: 'Adventuring Gear',
      cost: '300 gp',
      weight: '—',
      source: 'EGW',
    },
    {
      name: 'Blanket',
      type: 'Adventuring Gear',
      cost: '5 sp',
      weight: '3 lb.',
      source: 'PHB',
    },
    {
      name: 'Blasting Powder',
      type: 'Adventuring Gear',
      cost: '—',
      weight: '—',
      source: 'EGW',
    },
    {
      name: 'Blight Ichor',
      type: 'Adventuring Gear',
      cost: '200 gp',
      weight: '—',
      source: 'EGW',
    },
    {
      name: 'Block and Tackle',
      type: 'Adventuring Gear',
      cost: '1 gp',
      weight: '5 lb.',
      source: 'PHB',
    },
    {
      name: 'Blowgun',
      type: 'Martial Weapon, Ranged Weapon',
      cost: '10 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Blowgun Needle',
      type: 'Ammunition',
      cost: '2 cp',
      weight: '0.32 oz.',
      source: 'PHB',
    },
    {
      name: 'Blowgun Needles (50)',
      type: 'Ammunition',
      cost: '1 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Bombard',
      type: 'Vehicle (Space)',
      cost: '50,000 gp',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Book',
      type: 'Adventuring Gear',
      cost: '25 gp',
      weight: '5 lb.',
      source: 'PHB',
    },
    {
      name: 'Breastplate',
      type: 'Medium Armor',
      cost: '400 gp',
      weight: '20 lb.',
      source: 'PHB',
    },
    {
      name: 'Brewer`s Supplies',
      type: 'Artisan`s Tools',
      cost: '20 gp',
      weight: '9 lb.',
      source: 'PHB',
    },
    {
      name: 'Bucket',
      type: 'Adventuring Gear',
      cost: '5 cp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Bullseye Lantern',
      type: 'Adventuring Gear',
      cost: '10 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Burglar`s Pack',
      type: 'Adventuring Gear',
      cost: '16 gp',
      weight: '44½ lb.',
      source: 'PHB',
    },
    {
      name: 'Burnt Othur Fumes',
      type: 'Adventuring Gear, Poison',
      cost: '500 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Calligrapher`s Supplies',
      type: 'Artisan`s Tools',
      cost: '10 gp',
      weight: '5 lb.',
      source: 'PHB',
    },
    {
      name: 'Caltrop',
      type: 'Adventuring Gear',
      cost: '5 cp',
      weight: '1.6 oz.',
      source: 'PHB',
    },
    {
      name: 'Caltrops (bag of 20)',
      type: 'Adventuring Gear',
      cost: '1 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    { name: 'Camel', type: 'Mount', cost: '50 gp', weight: '—', source: 'PHB' },
    {
      name: 'Candle',
      type: 'Adventuring Gear',
      cost: '1 cp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Canvas (1 sq. yd.)',
      type: 'Trade Good',
      cost: '1 sp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Carpenter`s Tools',
      type: 'Artisan`s Tools',
      cost: '8 gp',
      weight: '6 lb.',
      source: 'PHB',
    },
    {
      name: 'Carriage',
      type: 'Vehicle (Land)',
      cost: '100 gp',
      weight: '600 lb.',
      source: 'PHB',
    },
    {
      name: 'Carrion Crawler Mucus',
      type: 'Adventuring Gear, Poison',
      cost: '200 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Cart',
      type: 'Vehicle (Land)',
      cost: '15 gp',
      weight: '200 lb.',
      source: 'PHB',
    },
    {
      name: 'Cartographer`s Tools',
      type: 'Artisan`s Tools',
      cost: '15 gp',
      weight: '6 lb.',
      source: 'PHB',
    },
    {
      name: 'Chain (10 feet)',
      type: 'Adventuring Gear',
      cost: '5 gp',
      weight: '10 lb.',
      source: 'PHB',
    },
    {
      name: 'Chain Mail',
      type: 'Heavy Armor',
      cost: '75 gp',
      weight: '55 lb.',
      source: 'PHB',
    },
    {
      name: 'Chain Shirt',
      type: 'Medium Armor',
      cost: '50 gp',
      weight: '20 lb.',
      source: 'PHB',
    },
    {
      name: 'Chalk (1 piece)',
      type: 'Adventuring Gear',
      cost: '1 cp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Chariot',
      type: 'Vehicle (Land)',
      cost: '250 gp',
      weight: '100 lb.',
      source: 'PHB',
    },
    {
      name: 'Chest',
      type: 'Adventuring Gear',
      cost: '5 gp',
      weight: '25 lb.',
      source: 'PHB',
    },
    {
      name: 'Chicken',
      type: 'Trade Good',
      cost: '2 cp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Chunk of Meat',
      type: 'Food and Drink',
      cost: '3 sp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Cinnamon',
      type: 'Trade Good',
      cost: '2 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Climber`s Kit',
      type: 'Adventuring Gear',
      cost: '25 gp',
      weight: '12 lb.',
      source: 'PHB',
    },
    {
      name: 'Cloves',
      type: 'Trade Good',
      cost: '3 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Club',
      type: 'Simple Weapon, Melee Weapon',
      cost: '1 sp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Cobbler`s Tools',
      type: 'Artisan`s Tools',
      cost: '5 gp',
      weight: '5 lb.',
      source: 'PHB',
    },
    {
      name: 'Common Clothes',
      type: 'Adventuring Gear',
      cost: '5 sp',
      weight: '3 lb.',
      source: 'PHB',
    },
    {
      name: 'Common Wine (Pitcher)',
      type: 'Food and Drink',
      cost: '2 sp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Component Pouch',
      type: 'Adventuring Gear',
      cost: '25 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Cook`s Utensils',
      type: 'Artisan`s Tools',
      cost: '1 gp',
      weight: '8 lb.',
      source: 'PHB',
    },
    {
      name: 'Copper',
      type: 'Trade Good',
      cost: '5 sp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Costume Clothes',
      type: 'Adventuring Gear',
      cost: '5 gp',
      weight: '4 lb.',
      source: 'PHB',
    },
    {
      name: 'Cotton Cloth (1 sq. yd.)',
      type: 'Trade Good',
      cost: '5 sp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Cow',
      type: 'Trade Good',
      cost: '10 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Crossbow Bolt',
      type: 'Ammunition',
      cost: '5 cp',
      weight: '1.2 oz.',
      source: 'PHB',
    },
    {
      name: 'Crossbow Bolt Case',
      type: 'Adventuring Gear',
      cost: '1 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Crossbow Bolts (20)',
      type: 'Ammunition',
      cost: '1 gp',
      weight: '1½ lb.',
      source: 'PHB',
    },
    {
      name: 'Crowbar',
      type: 'Adventuring Gear',
      cost: '2 gp',
      weight: '5 lb.',
      source: 'PHB',
    },
    {
      name: 'Crystal',
      type: 'Spellcasting Focus',
      cost: '10 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Dagger',
      type: 'Simple Weapon, Melee Weapon',
      cost: '2 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Damselfly Ship',
      type: 'Vehicle (Space)',
      cost: '20,000 gp',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Dart',
      type: 'Simple Weapon, Ranged Weapon',
      cost: '5 cp',
      weight: '¼ lb.',
      source: 'PHB',
    },
    {
      name: 'Dice Set',
      type: 'Gaming Set',
      cost: '1 sp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Diplomat`s Pack',
      type: 'Adventuring Gear',
      cost: '39 gp',
      weight: '36 lb.',
      source: 'PHB',
    },
    {
      name: 'Disguise Kit',
      type: 'Tools',
      cost: '25 gp',
      weight: '3 lb.',
      source: 'PHB',
    },
    { name: 'Donkey', type: 'Mount', cost: '8 gp', weight: '—', source: 'PHB' },
    {
      name: 'Double-Bladed Scimitar',
      type: 'Martial Weapon, Melee Weapon',
      cost: '100 gp',
      weight: '6 lb.',
      source: 'ERLW',
    },
    {
      name: 'Draft Horse',
      type: 'Mount',
      cost: '50 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Dragon`s Blood',
      type: 'Other',
      cost: '—',
      weight: '—',
      source: 'ERLW',
    },
    {
      name: 'Dragonchess Set',
      type: 'Gaming Set',
      cost: '1 gp',
      weight: '½ lb.',
      source: 'PHB',
    },
    {
      name: 'Dreamlily',
      type: 'Other',
      cost: '—',
      weight: '—',
      source: 'ERLW',
    },
    {
      name: 'Drow Poison',
      type: 'Adventuring Gear, Poison',
      cost: '200 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Druidic Focus',
      type: 'Spellcasting Focus',
      cost: '—',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Drum',
      type: 'Instrument',
      cost: '6 gp',
      weight: '3 lb.',
      source: 'PHB',
    },
    {
      name: 'Dulcimer',
      type: 'Instrument',
      cost: '25 gp',
      weight: '10 lb.',
      source: 'PHB',
    },
    {
      name: 'Dungeoneer`s Pack',
      type: 'Adventuring Gear',
      cost: '12 gp',
      weight: '61½ lb.',
      source: 'PHB',
    },
    {
      name: 'Dynamite',
      type: 'Explosive',
      cost: '100 gp',
      weight: '—',
      source: 'TDCSR',
    },
    {
      name: 'Elephant',
      type: 'Mount',
      cost: '200 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Elven Trinket',
      type: 'Adventuring Gear',
      cost: '—',
      weight: '—',
      source: 'MTF',
    },
    {
      name: 'Emblem',
      type: 'Spellcasting Focus',
      cost: '5 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Entertainer`s Pack',
      type: 'Adventuring Gear',
      cost: '40 gp',
      weight: '38 lb.',
      source: 'PHB',
    },
    {
      name: 'Essence of Ether',
      type: 'Adventuring Gear, Poison',
      cost: '300 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Exotic Saddle',
      type: 'Tack and Harness',
      cost: '60 gp',
      weight: '40 lb.',
      source: 'PHB',
    },
    {
      name: 'Explorer`s Pack',
      type: 'Adventuring Gear',
      cost: '10 gp',
      weight: '59 lb.',
      source: 'PHB',
    },
    {
      name: 'Explosive Seed',
      type: 'Adventuring Gear',
      cost: '—',
      weight: '—',
      source: 'EGW',
    },
    {
      name: 'Feed (per day)',
      type: 'Tack and Harness',
      cost: '5 cp',
      weight: '10 lb.',
      source: 'PHB',
    },
    {
      name: 'Fine Clothes',
      type: 'Adventuring Gear',
      cost: '15 gp',
      weight: '6 lb.',
      source: 'PHB',
    },
    {
      name: 'Fine Wine (Bottle)',
      type: 'Food and Drink',
      cost: '10 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Fishing Tackle',
      type: 'Adventuring Gear',
      cost: '1 gp',
      weight: '4 lb.',
      source: 'PHB',
    },
    {
      name: 'Flail',
      type: 'Martial Weapon, Melee Weapon',
      cost: '10 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Flask',
      type: 'Adventuring Gear',
      cost: '2 cp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Flensing Claws',
      type: 'Other',
      cost: '—',
      weight: '—',
      source: 'VGM',
    },
    {
      name: 'Flensing Claws (Huge)',
      type: 'Other',
      cost: '—',
      weight: '—',
      source: 'VGM',
    },
    {
      name: 'Flensing Claws (Large)',
      type: 'Other',
      cost: '—',
      weight: '—',
      source: 'VGM',
    },
    {
      name: 'Flensing Claws (Medium)',
      type: 'Other',
      cost: '—',
      weight: '—',
      source: 'VGM',
    },
    {
      name: 'Flensing Claws (Small)',
      type: 'Other',
      cost: '—',
      weight: '—',
      source: 'VGM',
    },
    {
      name: 'Flour',
      type: 'Trade Good',
      cost: '2 cp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Flute',
      type: 'Instrument',
      cost: '2 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Flying Fish Ship',
      type: 'Vehicle (Space)',
      cost: '20,000 gp',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Forgery Kit',
      type: 'Tools',
      cost: '15 gp',
      weight: '5 lb.',
      source: 'PHB',
    },
    {
      name: 'Galley',
      type: 'Vehicle',
      cost: '30,000 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Gaming Set',
      type: 'Gaming Set',
      cost: '—',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Ginger',
      type: 'Trade Good',
      cost: '1 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Glaive',
      type: 'Martial Weapon, Melee Weapon',
      cost: '20 gp',
      weight: '6 lb.',
      source: 'PHB',
    },
    {
      name: 'Glass Bottle',
      type: 'Adventuring Gear',
      cost: '2 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Glassblowers Tools',
      type: 'Artisan`s Tools',
      cost: '30 gp',
      weight: '5 lb.',
      source: 'PHB',
    },
    {
      name: 'Glaur',
      type: 'Instrument',
      cost: '—',
      weight: '—',
      source: 'SCAG',
    },
    {
      name: 'Gluebomb',
      type: 'Explosive',
      cost: '50 gp',
      weight: '—',
      source: 'TDCSR',
    },
    {
      name: 'Goat',
      type: 'Trade Good',
      cost: '1 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Gold',
      type: 'Trade Good',
      cost: '50 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Grappling Hook',
      type: 'Adventuring Gear',
      cost: '2 gp',
      weight: '4 lb.',
      source: 'PHB',
    },
    {
      name: 'Greataxe',
      type: 'Martial Weapon, Melee Weapon',
      cost: '30 gp',
      weight: '7 lb.',
      source: 'PHB',
    },
    {
      name: 'Greatclub',
      type: 'Simple Weapon, Melee Weapon',
      cost: '2 sp',
      weight: '10 lb.',
      source: 'PHB',
    },
    {
      name: 'Greatsword',
      type: 'Martial Weapon, Melee Weapon',
      cost: '50 gp',
      weight: '6 lb.',
      source: 'PHB',
    },
    {
      name: 'Halberd',
      type: 'Martial Weapon, Melee Weapon',
      cost: '20 gp',
      weight: '6 lb.',
      source: 'PHB',
    },
    {
      name: 'Half Plate Armor',
      type: 'Medium Armor',
      cost: '750 gp',
      weight: '40 lb.',
      source: 'PHB',
    },
    {
      name: 'Hammer',
      type: 'Adventuring Gear',
      cost: '1 gp',
      weight: '3 lb.',
      source: 'PHB',
    },
    {
      name: 'Hammerhead Ship',
      type: 'Vehicle (Space)',
      cost: '40,000 gp',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Hand Crossbow',
      type: 'Martial Weapon, Ranged Weapon',
      cost: '75 gp',
      weight: '3 lb.',
      source: 'PHB',
    },
    {
      name: 'Hand Drum',
      type: 'Instrument',
      cost: '—',
      weight: '—',
      source: 'SCAG',
    },
    {
      name: 'Handaxe',
      type: 'Simple Weapon, Melee Weapon',
      cost: '5 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Healer`s Kit',
      type: 'Adventuring Gear',
      cost: '5 gp',
      weight: '3 lb.',
      source: 'PHB',
    },
    {
      name: 'Heavy Crossbow',
      type: 'Martial Weapon, Ranged Weapon',
      cost: '50 gp',
      weight: '18 lb.',
      source: 'PHB',
    },
    {
      name: 'Hempen Rope (50 feet)',
      type: 'Adventuring Gear',
      cost: '1 gp',
      weight: '10 lb.',
      source: 'PHB',
    },
    {
      name: 'Herbalism Kit',
      type: 'Tools',
      cost: '5 gp',
      weight: '3 lb.',
      source: 'PHB',
    },
    {
      name: 'Hide Armor',
      type: 'Medium Armor',
      cost: '10 gp',
      weight: '12 lb.',
      source: 'PHB',
    },
    {
      name: 'Holy Symbol',
      type: 'Spellcasting Focus',
      cost: '—',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Holy Water (flask)',
      type: 'Adventuring Gear',
      cost: '25 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Hooded Lantern',
      type: 'Adventuring Gear',
      cost: '5 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Horn',
      type: 'Instrument',
      cost: '3 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Horror Trinket',
      type: 'Adventuring Gear',
      cost: '—',
      weight: '—',
      source: 'VRGR',
    },
    {
      name: 'Hourglass',
      type: 'Adventuring Gear',
      cost: '25 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Hunk of Cheese',
      type: 'Food and Drink',
      cost: '1 sp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Hunting Trap',
      type: 'Adventuring Gear',
      cost: '5 gp',
      weight: '25 lb.',
      source: 'PHB',
    },
    {
      name: 'Ink (1-ounce bottle)',
      type: 'Adventuring Gear',
      cost: '10 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Ink Pen',
      type: 'Adventuring Gear',
      cost: '2 cp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Iron',
      type: 'Trade Good',
      cost: '1 sp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Iron Pot',
      type: 'Adventuring Gear',
      cost: '2 gp',
      weight: '10 lb.',
      source: 'PHB',
    },
    {
      name: 'Iron Spike',
      type: 'Adventuring Gear',
      cost: '1 sp',
      weight: '½ lb.',
      source: 'PHB',
    },
    {
      name: 'Iron Spikes (10)',
      type: 'Adventuring Gear',
      cost: '1 gp',
      weight: '5 lb.',
      source: 'PHB',
    },
    {
      name: 'Ivana`s Whisper',
      type: 'Adventuring Gear, Poison',
      cost: '—',
      weight: '—',
      source: 'VRGR',
    },
    {
      name: 'Javelin',
      type: 'Simple Weapon, Melee Weapon',
      cost: '5 sp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Jeweler`s Tools',
      type: 'Artisan`s Tools',
      cost: '25 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Jug',
      type: 'Adventuring Gear',
      cost: '2 cp',
      weight: '4 lb.',
      source: 'PHB',
    },
    {
      name: 'Keelboat',
      type: 'Vehicle',
      cost: '3,000 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Ladder (10-foot)',
      type: 'Adventuring Gear',
      cost: '1 sp',
      weight: '25 lb.',
      source: 'PHB',
    },
    {
      name: 'Lamp',
      type: 'Adventuring Gear',
      cost: '5 sp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Lamprey Ship',
      type: 'Vehicle (Space)',
      cost: '20,000 gp',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Lance',
      type: 'Martial Weapon, Melee Weapon',
      cost: '10 gp',
      weight: '6 lb.',
      source: 'PHB',
    },
    {
      name: 'Leather Armor',
      type: 'Light Armor',
      cost: '10 gp',
      weight: '10 lb.',
      source: 'PHB',
    },
    {
      name: 'Leatherworker`s Tools',
      type: 'Artisan`s Tools',
      cost: '5 gp',
      weight: '5 lb.',
      source: 'PHB',
    },
    {
      name: 'Light Crossbow',
      type: 'Simple Weapon, Ranged Weapon',
      cost: '25 gp',
      weight: '5 lb.',
      source: 'PHB',
    },
    {
      name: 'Light Hammer',
      type: 'Simple Weapon, Melee Weapon',
      cost: '2 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Linen (1 sq. yd.)',
      type: 'Trade Good',
      cost: '5 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Living Ship',
      type: 'Vehicle (Space)',
      cost: '25,000 gp',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Loaf of Bread',
      type: 'Food and Drink',
      cost: '2 cp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Lock',
      type: 'Adventuring Gear',
      cost: '10 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Longbow',
      type: 'Martial Weapon, Ranged Weapon',
      cost: '50 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Longhorn',
      type: 'Instrument',
      cost: '—',
      weight: '—',
      source: 'SCAG',
    },
    {
      name: 'Longship',
      type: 'Vehicle',
      cost: '10,000 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Longsword',
      type: 'Martial Weapon, Melee Weapon',
      cost: '15 gp',
      weight: '3 lb.',
      source: 'PHB',
    },
    {
      name: 'Lute',
      type: 'Instrument',
      cost: '35 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Lyre',
      type: 'Instrument',
      cost: '30 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Mace',
      type: 'Simple Weapon, Melee Weapon',
      cost: '5 gp',
      weight: '4 lb.',
      source: 'PHB',
    },
    {
      name: 'Magnifying Glass',
      type: 'Adventuring Gear',
      cost: '100 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Malice',
      type: 'Adventuring Gear, Poison',
      cost: '250 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Manacles',
      type: 'Adventuring Gear',
      cost: '2 gp',
      weight: '6 lb.',
      source: 'PHB',
    },
    {
      name: 'Map or Scroll Case',
      type: 'Adventuring Gear',
      cost: '1 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Mason`s Tools',
      type: 'Artisan`s Tools',
      cost: '10 gp',
      weight: '8 lb.',
      source: 'PHB',
    },
    {
      name: 'Mastiff',
      type: 'Mount',
      cost: '25 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Maul',
      type: 'Martial Weapon, Melee Weapon',
      cost: '10 gp',
      weight: '10 lb.',
      source: 'PHB',
    },
    {
      name: 'Merchant`s Scale',
      type: 'Adventuring Gear',
      cost: '5 gp',
      weight: '3 lb.',
      source: 'PHB',
    },
    {
      name: 'Mess Kit',
      type: 'Adventuring Gear',
      cost: '2 sp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Midnight Tears',
      type: 'Adventuring Gear, Poison',
      cost: '1,500 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Military Saddle',
      type: 'Tack and Harness',
      cost: '20 gp',
      weight: '30 lb.',
      source: 'PHB',
    },
    {
      name: 'Miner`s Pick',
      type: 'Adventuring Gear',
      cost: '2 gp',
      weight: '10 lb.',
      source: 'PHB',
    },
    {
      name: 'Monster Hunter`s Pack',
      type: 'Adventuring Gear',
      cost: '33 gp',
      weight: '48½ lb.',
      source: 'VRGR',
    },
    {
      name: 'Moorbounder',
      type: 'Mount',
      cost: '400 gp',
      weight: '—',
      source: 'EGW',
    },
    {
      name: 'Morningstar',
      type: 'Martial Weapon, Melee Weapon',
      cost: '15 gp',
      weight: '4 lb.',
      source: 'PHB',
    },
    { name: 'Mule', type: 'Mount', cost: '8 gp', weight: '—', source: 'PHB' },
    {
      name: 'Muroosa Balm',
      type: 'Adventuring Gear',
      cost: '100 gp',
      weight: '—',
      source: 'EGW',
    },
    {
      name: 'Musical Instrument',
      type: 'Instrument',
      cost: '—',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Musical Instrument',
      type: 'Instrument',
      cost: '—',
      weight: '—',
      source: 'SCAG',
    },
    {
      name: 'Nautiloid',
      type: 'Vehicle (Space)',
      cost: '50,000 gp',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Navigator`s Tools',
      type: 'Tools',
      cost: '25 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Net',
      type: 'Martial Weapon, Ranged Weapon',
      cost: '1 gp',
      weight: '3 lb.',
      source: 'PHB',
    },
    {
      name: 'Nightspider',
      type: 'Vehicle (Space)',
      cost: '50,000 gp',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Oil (flask)',
      type: 'Adventuring Gear',
      cost: '1 sp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Oil of Taggit',
      type: 'Adventuring Gear, Poison',
      cost: '400 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Olisuba Leaf',
      type: 'Adventuring Gear',
      cost: '50 gp',
      weight: '—',
      source: 'EGW',
    },
    {
      name: 'Oloore Root Teabag',
      type: 'Illegal Drug',
      cost: '100 gp',
      weight: '—',
      source: 'TDCSR',
    },
    {
      name: 'Orb',
      type: 'Spellcasting Focus',
      cost: '20 gp',
      weight: '3 lb.',
      source: 'PHB',
    },
    {
      name: 'Ox',
      type: 'Trade Good',
      cost: '15 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Pack Saddle',
      type: 'Tack and Harness',
      cost: '5 gp',
      weight: '15 lb.',
      source: 'PHB',
    },
    {
      name: 'Padded Armor',
      type: 'Light Armor',
      cost: '5 gp',
      weight: '8 lb.',
      source: 'PHB',
    },
    {
      name: 'Painter`s Supplies',
      type: 'Artisan`s Tools',
      cost: '10 gp',
      weight: '5 lb.',
      source: 'PHB',
    },
    {
      name: 'Pale Tincture',
      type: 'Adventuring Gear, Poison',
      cost: '250 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Pan Flute',
      type: 'Instrument',
      cost: '12 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Paper (one sheet)',
      type: 'Adventuring Gear',
      cost: '2 sp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Parchment (one sheet)',
      type: 'Adventuring Gear',
      cost: '1 sp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Pepper',
      type: 'Trade Good',
      cost: '2 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Perfume (vial)',
      type: 'Adventuring Gear',
      cost: '5 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Pig',
      type: 'Trade Good',
      cost: '3 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Pike',
      type: 'Martial Weapon, Melee Weapon',
      cost: '5 gp',
      weight: '18 lb.',
      source: 'PHB',
    },
    {
      name: 'Pitcher',
      type: 'Adventuring Gear',
      cost: '2 cp',
      weight: '4 lb.',
      source: 'PHB',
    },
    {
      name: 'Piton',
      type: 'Adventuring Gear',
      cost: '5 cp',
      weight: '¼ lb.',
      source: 'PHB',
    },
    {
      name: 'Plainscow',
      type: 'Mount',
      cost: '200 gp',
      weight: '—',
      source: 'TDCSR',
    },
    {
      name: 'Plate Armor',
      type: 'Heavy Armor',
      cost: '1,500 gp',
      weight: '65 lb.',
      source: 'PHB',
    },
    {
      name: 'Platinum',
      type: 'Trade Good',
      cost: '500 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Playing Card Set',
      type: 'Gaming Set',
      cost: '5 sp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Poisoner`s Kit',
      type: 'Tools',
      cost: '50 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Pole (10-foot)',
      type: 'Adventuring Gear',
      cost: '5 cp',
      weight: '7 lb.',
      source: 'PHB',
    },
    { name: 'Pony', type: 'Mount', cost: '30 gp', weight: '—', source: 'PHB' },
    {
      name: 'Portable Ram',
      type: 'Adventuring Gear',
      cost: '4 gp',
      weight: '35 lb.',
      source: 'PHB',
    },
    {
      name: 'Potter`s Tools',
      type: 'Artisan`s Tools',
      cost: '10 gp',
      weight: '3 lb.',
      source: 'PHB',
    },
    {
      name: 'Pouch',
      type: 'Adventuring Gear',
      cost: '5 sp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Pride Silk',
      type: 'Adventuring Gear',
      cost: '100 gp',
      weight: '1 lb.',
      source: 'EGW',
    },
    {
      name: 'Pride Silk Outfit',
      type: 'Adventuring Gear',
      cost: '500 gp',
      weight: '4 lb.',
      source: 'EGW',
    },
    {
      name: 'Priest`s Pack',
      type: 'Adventuring Gear',
      cost: '19 gp',
      weight: '24 lb.',
      source: 'PHB',
    },
    {
      name: 'Purple Worm Poison',
      type: 'Adventuring Gear, Poison',
      cost: '2,000 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Quarterstaff',
      type: 'Simple Weapon, Melee Weapon',
      cost: '2 sp',
      weight: '4 lb.',
      source: 'PHB',
    },
    {
      name: 'Quiver',
      type: 'Adventuring Gear',
      cost: '1 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Rapier',
      type: 'Martial Weapon, Melee Weapon',
      cost: '25 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Rations (1 day)',
      type: 'Adventuring Gear',
      cost: '5 sp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Reliquary',
      type: 'Spellcasting Focus',
      cost: '5 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Riding Horse',
      type: 'Mount',
      cost: '75 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Riding Saddle',
      type: 'Tack and Harness',
      cost: '10 gp',
      weight: '25 lb.',
      source: 'PHB',
    },
    {
      name: 'Ring Mail',
      type: 'Heavy Armor',
      cost: '30 gp',
      weight: '40 lb.',
      source: 'PHB',
    },
    {
      name: 'Robes',
      type: 'Adventuring Gear',
      cost: '1 gp',
      weight: '4 lb.',
      source: 'PHB',
    },
    {
      name: 'Rod',
      type: 'Spellcasting Focus',
      cost: '10 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Rowboat',
      type: 'Vehicle',
      cost: '50 gp',
      weight: '100 lb.',
      source: 'DMG',
    },
    {
      name: 'Sack',
      type: 'Adventuring Gear',
      cost: '1 cp',
      weight: '½ lb.',
      source: 'PHB',
    },
    {
      name: 'Saddlebags',
      type: 'Tack and Harness',
      cost: '4 gp',
      weight: '8 lb.',
      source: 'PHB',
    },
    {
      name: 'Saffron',
      type: 'Trade Good',
      cost: '15 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Sailing Ship',
      type: 'Vehicle',
      cost: '10,000 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Salt',
      type: 'Trade Good',
      cost: '5 cp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Scale Mail',
      type: 'Medium Armor',
      cost: '50 gp',
      weight: '45 lb.',
      source: 'PHB',
    },
    {
      name: 'Scholar`s Pack',
      type: 'Adventuring Gear',
      cost: '40 gp',
      weight: '10 lb.',
      source: 'PHB',
    },
    {
      name: 'Scimitar',
      type: 'Martial Weapon, Melee Weapon',
      cost: '25 gp',
      weight: '3 lb.',
      source: 'PHB',
    },
    {
      name: 'Scorpion Ship',
      type: 'Vehicle (Space)',
      cost: '25,000 gp',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Sealing Wax',
      type: 'Adventuring Gear',
      cost: '5 sp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Serpent Venom',
      type: 'Adventuring Gear, Poison',
      cost: '200 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Shawm',
      type: 'Instrument',
      cost: '2 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Shawm',
      type: 'Instrument',
      cost: '—',
      weight: '—',
      source: 'SCAG',
    },
    {
      name: 'Sheep',
      type: 'Trade Good',
      cost: '2 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Shield',
      type: 'Shield',
      cost: '10 gp',
      weight: '6 lb.',
      source: 'PHB',
    },
    {
      name: 'Shortbow',
      type: 'Simple Weapon, Ranged Weapon',
      cost: '25 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Shortsword',
      type: 'Martial Weapon, Melee Weapon',
      cost: '10 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Shovel',
      type: 'Adventuring Gear',
      cost: '2 gp',
      weight: '5 lb.',
      source: 'PHB',
    },
    {
      name: 'Shrike Ship',
      type: 'Vehicle (Space)',
      cost: '20,000 gp',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Sickle',
      type: 'Simple Weapon, Melee Weapon',
      cost: '1 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Signal Whistle',
      type: 'Adventuring Gear',
      cost: '5 cp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Signet Ring',
      type: 'Adventuring Gear',
      cost: '5 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Silk (1 sq. yd.)',
      type: 'Trade Good',
      cost: '10 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Silk Rope (50 feet)',
      type: 'Adventuring Gear',
      cost: '10 gp',
      weight: '5 lb.',
      source: 'PHB',
    },
    {
      name: 'Silver',
      type: 'Trade Good',
      cost: '5 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Silvered Ammunition',
      type: 'Ammunition, Generic Variant',
      cost: '—',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Silvered Weapon',
      type: 'Generic Variant',
      cost: '—',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Skyship',
      type: 'Vehicle',
      cost: '100,000 gp',
      weight: '—',
      source: 'EGW',
    },
    {
      name: 'Skyship',
      type: 'Vehicle',
      cost: '100,000 gp',
      weight: '—',
      source: 'TDCSR',
    },
    {
      name: 'Sled',
      type: 'Vehicle (Land)',
      cost: '20 gp',
      weight: '300 lb.',
      source: 'PHB',
    },
    {
      name: 'Sledgehammer',
      type: 'Adventuring Gear',
      cost: '2 gp',
      weight: '10 lb.',
      source: 'PHB',
    },
    {
      name: 'Sling',
      type: 'Simple Weapon, Ranged Weapon',
      cost: '1 sp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Sling Bullet',
      type: 'Ammunition',
      cost: '0.2 cp',
      weight: '1.2 oz.',
      source: 'PHB',
    },
    {
      name: 'Sling Bullets (20)',
      type: 'Ammunition',
      cost: '4 cp',
      weight: '1½ lb.',
      source: 'PHB',
    },
    {
      name: 'Smith`s Tools',
      type: 'Artisan`s Tools',
      cost: '20 gp',
      weight: '8 lb.',
      source: 'PHB',
    },
    {
      name: 'Soap',
      type: 'Adventuring Gear',
      cost: '2 cp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Songhorn',
      type: 'Instrument',
      cost: '—',
      weight: '—',
      source: 'SCAG',
    },
    {
      name: 'Soothsalts',
      type: 'Adventuring Gear',
      cost: '150 gp',
      weight: '—',
      source: 'EGW',
    },
    {
      name: 'Space Galleon',
      type: 'Vehicle (Space)',
      cost: '30,000 gp',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Spear',
      type: 'Simple Weapon, Melee Weapon',
      cost: '1 gp',
      weight: '3 lb.',
      source: 'PHB',
    },
    {
      name: 'Spellbook',
      type: 'Adventuring Gear',
      cost: '50 gp',
      weight: '3 lb.',
      source: 'PHB',
    },
    {
      name: 'Spiked Armor',
      type: 'Medium Armor',
      cost: '75 gp',
      weight: '45 lb.',
      source: 'SCAG',
    },
    {
      name: 'Splint Armor',
      type: 'Heavy Armor',
      cost: '200 gp',
      weight: '60 lb.',
      source: 'PHB',
    },
    {
      name: 'Sprig of Mistletoe',
      type: 'Spellcasting Focus',
      cost: '1 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Spyglass',
      type: 'Adventuring Gear',
      cost: '1,000 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Squid Ship',
      type: 'Vehicle (Space)',
      cost: '25,000 gp',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Stabling (per day)',
      type: 'Tack and Harness',
      cost: '5 sp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Staff',
      type: 'Staff, Simple Weapon, Melee Weapon, Spellcasting Focus',
      cost: '5 gp',
      weight: '4 lb.',
      source: 'PHB',
    },
    {
      name: 'Star Moth',
      type: 'Vehicle (Space)',
      cost: '40,000 gp',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Steel Mirror',
      type: 'Adventuring Gear',
      cost: '5 gp',
      weight: '½ lb.',
      source: 'PHB',
    },
    {
      name: 'Stink Bomb',
      type: 'Explosive',
      cost: '25 gp',
      weight: '—',
      source: 'TDCSR',
    },
    {
      name: 'Studded Leather Armor',
      type: 'Light Armor',
      cost: '45 gp',
      weight: '13 lb.',
      source: 'PHB',
    },
    {
      name: 'Survival Mantle',
      type: 'Medium Armor',
      cost: '—',
      weight: '40 lb.',
      source: 'VGM',
    },
    {
      name: 'Tankard',
      type: 'Adventuring Gear',
      cost: '2 cp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Tantan',
      type: 'Instrument',
      cost: '—',
      weight: '—',
      source: 'SCAG',
    },
    {
      name: 'Theki Root',
      type: 'Adventuring Gear',
      cost: '3 gp',
      weight: '—',
      source: 'EGW',
    },
    {
      name: 'Thelarr',
      type: 'Instrument',
      cost: '—',
      weight: '—',
      source: 'SCAG',
    },
    {
      name: 'Thieves` Tools',
      type: 'Tools',
      cost: '25 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Three-Dragon Ante Set',
      type: 'Gaming Set',
      cost: '1 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Tinderbox',
      type: 'Adventuring Gear',
      cost: '5 sp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Tinker`s Tools',
      type: 'Artisan`s Tools',
      cost: '50 gp',
      weight: '10 lb.',
      source: 'PHB',
    },
    {
      name: 'Tocken',
      type: 'Instrument',
      cost: '—',
      weight: '—',
      source: 'SCAG',
    },
    {
      name: 'Torch',
      type: 'Adventuring Gear',
      cost: '1 cp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Torpor',
      type: 'Adventuring Gear, Poison',
      cost: '600 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Totem',
      type: 'Spellcasting Focus',
      cost: '1 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Traveler`s Clothes',
      type: 'Adventuring Gear',
      cost: '2 gp',
      weight: '4 lb.',
      source: 'PHB',
    },
    {
      name: 'Trident',
      type: 'Martial Weapon, Melee Weapon',
      cost: '5 gp',
      weight: '4 lb.',
      source: 'PHB',
    },
    {
      name: 'Trinket',
      type: 'Adventuring Gear',
      cost: '—',
      weight: '—',
      source: 'AI',
    },
    {
      name: 'Trinket',
      type: 'Adventuring Gear',
      cost: '—',
      weight: '—',
      source: 'EET',
    },
    {
      name: 'Trinket',
      type: 'Adventuring Gear',
      cost: '—',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Truth Serum',
      type: 'Adventuring Gear, Poison',
      cost: '150 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Turtle Ship',
      type: 'Vehicle (Space)',
      cost: '40,000 gp',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Two-Person Tent',
      type: 'Adventuring Gear',
      cost: '2 gp',
      weight: '20 lb.',
      source: 'PHB',
    },
    {
      name: 'Tyrant Ship',
      type: 'Vehicle (Space)',
      cost: '—',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Vial',
      type: 'Adventuring Gear',
      cost: '1 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Viol',
      type: 'Instrument',
      cost: '30 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Wagon',
      type: 'Vehicle (Land)',
      cost: '35 gp',
      weight: '400 lb.',
      source: 'PHB',
    },
    {
      name: 'Wand',
      type: 'Spellcasting Focus',
      cost: '10 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'War Pick',
      type: 'Martial Weapon, Melee Weapon',
      cost: '5 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Wargong',
      type: 'Instrument',
      cost: '—',
      weight: '—',
      source: 'SCAG',
    },
    {
      name: 'Warhammer',
      type: 'Martial Weapon, Melee Weapon',
      cost: '15 gp',
      weight: '2 lb.',
      source: 'PHB',
    },
    {
      name: 'Warhorse',
      type: 'Mount',
      cost: '400 gp',
      weight: '—',
      source: 'PHB',
    },
    {
      name: 'Warship',
      type: 'Vehicle',
      cost: '25,000 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Wasp Ship',
      type: 'Vehicle (Space)',
      cost: '20,000 gp',
      weight: '—',
      source: 'AAG',
    },
    {
      name: 'Waterskin',
      type: 'Adventuring Gear',
      cost: '2 sp',
      weight: '5 lb. (full)',
      source: 'PHB',
    },
    {
      name: 'Weaver`s Tools',
      type: 'Artisan`s Tools',
      cost: '1 gp',
      weight: '5 lb.',
      source: 'PHB',
    },
    {
      name: 'Wheat',
      type: 'Trade Good',
      cost: '1 cp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Whetstone',
      type: 'Adventuring Gear',
      cost: '1 cp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Whip',
      type: 'Martial Weapon, Melee Weapon',
      cost: '2 gp',
      weight: '3 lb.',
      source: 'PHB',
    },
    {
      name: 'Willowshade Oil',
      type: 'Adventuring Gear',
      cost: '30 gp',
      weight: '—',
      source: 'EGW',
    },
    {
      name: 'Woodcarver`s Tools',
      type: 'Artisan`s Tools',
      cost: '1 gp',
      weight: '5 lb.',
      source: 'PHB',
    },
    {
      name: 'Wooden Staff',
      type: 'Simple Weapon, Spellcasting Focus',
      cost: '5 gp',
      weight: '4 lb.',
      source: 'PHB',
    },
    {
      name: 'Writing Kit',
      type: 'Adventuring Gear',
      cost: '—',
      weight: '—',
      source: 'TDCSR',
    },
    {
      name: 'Wyvern Poison',
      type: 'Adventuring Gear, Poison',
      cost: '1,200 gp',
      weight: '—',
      source: 'DMG',
    },
    {
      name: 'Yarting',
      type: 'Instrument',
      cost: '—',
      weight: '—',
      source: 'SCAG',
    },
    {
      name: 'Yew Wand',
      type: 'Spellcasting Focus',
      cost: '10 gp',
      weight: '1 lb.',
      source: 'PHB',
    },
    {
      name: 'Zeal',
      type: 'Illegal Drug',
      cost: '150 gp',
      weight: '—',
      source: 'TDCSR',
    },
  ]);

  class Container {
    name;
    type;
    contents;

    constructor(name = '', type, contents) {
      this.name = name;
      this.type = type;
      this.contents = contents;
    }
  }

  function getItemByName(name) {
    let item;
    for (let i = 0; i < itemVault.length; i++) {
      if (itemVault[i].name == name) {
        item = itemVault[i];
        i = itemVault.length;
      }
    }
  }

  function translateIntoItems(src) {
    const regex = /\[([^\]]+)\]/g;

    let result;
    let maches = [];
    let outcome = [];

    while ((result = regex.exec(src)) !== null) {
      maches.push(result);
    }

    for (let i = 0; i < maches.length; i++) {
      outcome.push(translatedSrc, getItemByName(maches[i]));
    }

    return outcome;
  }

  return (
    <div>
      <Head>
        <title>Loot Keeper</title>
      </Head>
      <main>
        <div>
          <label htmlFor="name">Name</label>
          <br />
          <input
            id="name"
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
          />
          <br />
          <label htmlFor="type">Type*</label>
          <br />
          <input
            id="type"
            type="text"
            value={type}
            onChange={(e) => setType(e.target.value)}
          />
          <br />
          <label htmlFor="contents">Contents*</label>
          <br />
          <textarea
            id="contents"
            type="text"
            value={contents}
            onChange={(e) => setContents(e.target.value)}
          />
          <br />
          <br />
          <button
            onClick={() => {
              setContainers(
                containers,
                containers.push(
                  new Container(name, type, translateIntoItems(contents))
                )
              ),
                console.log(containers);
            }}
          >
            Create!
          </button>
        </div>

        <div>
          <div>
            {containers.map((container, index) => {
              return <div key={index}>{container.name}</div>;
            })}
          </div>
        </div>
      </main>
    </div>
  );
}
